@AspNetCoreWebApiErrorHandlingMiddleware_HostAddress = http://localhost:5128

GET {{AspNetCoreWebApiErrorHandlingMiddleware_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{AspNetCoreWebApiErrorHandlingMiddleware_HostAddress}}/minimal


###
GET {{AspNetCoreWebApiErrorHandlingMiddleware_HostAddress}}/minimal/invalid